### PR TITLE
Added games.mmo, games.platformer, office.maths, programming.ide components

### PR DESCRIPTION
**Pull request by JoshStrobl**
Adds more gaming components, programming.ide to represent non-generic editors, and office.maths for software more oriented towards academy and mathematics.

**Icons (all from Moka):**
- `games.mmo`: `battlenet.png`
- `games.platformer`: `eufloria.png` **maybe???**
- `office.maths`: `matlab.png`
- `programming.ide`: `atom.png`

### CODE REVIEW

**Comment by ikeydoherty** [comment]
We have games.rpg - why is this here again?

**Comment by JoshStrobl** [comment]
Because none of these are necessarily RPG related. Platformer games don't necessary imply role-playing, nor does MMO.

Example: Terraria is a platformer game. However, it is not an RPG.

**Comment by ikeydoherty** [comment]
Read the diff wrong sorry, looked like you put in a second `games.rpg`

**Comment by JoshStrobl** [comment]
Ah, no problem :smile:

**Comment by ikeydoherty** [comment]
sorry. oops xD

**Pull request merged**
