### PR TITLE
Centralise pkg view

### PR DESCRIPTION
**Pull request by nextgensparx**
All pages that use a tree view to display a list of packages now extend a basic class called ScPackagesView. This view handles generating the tree view, scrolled window and loading page. Child classes can set the loading page message using set_message.

This is so that changes, such as showing if a package is installed, are easier to make across all the views; groups, installed and search results. The updates view was excluded as it seems to be fairly separate in what data it displays. I need some advice on that one.

To avoid confusion, package_view is now called installed_view and ScPackageView is ScInstalledView. This also describes it's role more accurately.

Since the translatable lines have changed, the .po files have also been updated.

Not sure if all of this is OK so please let me know what you think. Is this centralisation a good idea? Is there some reason this wasn't done earlier? I plan to make more improvements but this is the first step.

### CODE REVIEW

**Comment by nextgensparx** [comment]
I have had some issues when using this centralised package view. If I set a variable in ScPackagesView and then overwrite it in one of the child views, it seems to change in all other child views. Can I get some advice on why this is? I am still fairly new to GTK and I think it has something to do with it.

**Comment by ikeydoherty** [comment]
After much deliberation I'm gonna rebase your work on mine, instead of the other way around. My `snaps-yo` branch is 117 commits ahead and the pair of them are nightmare to put together. However, yours is good work against master and I let my work go stale, so, shame on me.

I'm going to merge your work, and I believe it will help simplify the codepath for snaps. Thank you for doing this! Do be warned, I'm about to let loose with everything I've got on `master` now, so follow up PRs won't be possible until that settles.

I'll also be changing so much of the existing code that if I run into your described issue, I'll get it fixed :D

BTW - congrats on being brave enough to tackle the SC!!! I look forward to potentially working with you on more areas in the SC once the dust settles :D

**Comment by nextgensparx** [comment]
@ikeydoherty Great!

Let me know when you are done because I would like to tackle #45, #96 and possibly #55, unless you are already tackling those.

Be the change you want to see in the world :) I look forward to working with you too.

**Comment by ikeydoherty** [comment]
I'll be changing pretty much everything that all of those depend on :)

**Comment by nextgensparx** [comment]
Well, I'll still be happy to help when the dust settles. Good luck!

**Pull request merged**
