### PR TITLE
Fix SC printing "Removed x of x" when installing

### PR DESCRIPTION
**Pull request by Staudey**

### CODE REVIEW

**Comment by Staudey** [comment]
I also noticed that it doesn't print the name of the current package. Should be "Removed/Installed/Updated X of X: [Package]", instead it just prints "Removed/Installed/Updated X of X:". Args for the "removed/installed/updated" status signals seem to be empty save for args[0]. I don't have enough experience to know where to go from here.

**Comment by ikeydoherty** [comment]
All looks good to me though, thanks!

**Comment by Staudey** [comment]
Well, I guess it's at least better (or less confusing) than before :smile:

**Comment by ikeydoherty** [comment]
Sure enough lol - this is now in the latest updates, cheers bud :)

**Pull request merged**
